basePath: /
definitions:
  db.CatalogItem:
    properties:
      categoria_id:
        type: string
      creador_id:
        type: string
      descripcion:
        type: string
      dimension_id:
        type: string
      entorno_id:
        type: string
      evidencia_requerida:
        type: string
      fecha_creacion:
        type: string
      fecha_vencimiento:
        type: string
      horas:
        type: integer
      id:
        type: string
      nombre:
        type: string
      puntaje:
        type: integer
      trascendencia_id:
        type: string
    type: object
  handlers.completarAdministrativoReq:
    properties:
      cargo:
        type: string
    type: object
  handlers.completarCreadorReq:
    properties:
      descripcion:
        type: string
      institucion:
        type: string
      tipo:
        description: Maestro, Tutor, Externa, etc.
        type: string
    type: object
  handlers.completarPerfilReq:
    properties:
      carrera:
        type: string
      cuatrimestre:
        type: integer
      grupo:
        type: string
      matricula:
        type: string
      tutor:
        type: string
    type: object
  handlers.loginReq:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handlers.registerReq:
    properties:
      apellido_materno:
        type: string
      apellido_paterno:
        type: string
      email:
        type: string
      nombre:
        type: string
      password:
        type: string
      role:
        type: string
      telefono:
        type: string
    type: object
  handlers.saveTDIReq:
    properties:
      categoria_id:
        type: string
      descripcion:
        type: string
      dimension_id:
        type: string
      entorno_id:
        type: string
      evidencia_requerida:
        type: string
      fecha_vencimiento:
        description: Formato AAAA-MM-DD
        type: string
      horas:
        type: integer
      nombre:
        type: string
      puntaje:
        type: integer
      trascendencia_id:
        type: string
    type: object
  handlers.selectTDIReq:
    properties:
      catalogo_tdi_id:
        type: string
    type: object
  handlers.tokenResp:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
  models.PerfilAdministrativo:
    properties:
      cargo:
        type: string
    type: object
  models.PerfilAlumno:
    properties:
      carrera:
        type: string
      cuatrimestre:
        type: integer
      grupo:
        type: string
      horas_acumuladas:
        type: integer
      matricula:
        type: string
      meta_horas:
        type: integer
      tutor:
        type: string
    type: object
  models.PerfilCreador:
    properties:
      descripcion:
        type: string
      institucion:
        type: string
      tipo:
        type: string
    type: object
  models.User:
    properties:
      activo:
        type: boolean
      apellido_materno:
        type: string
      apellido_paterno:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      nombre:
        type: string
      perfil_administrativo:
        $ref: '#/definitions/models.PerfilAdministrativo'
      perfil_alumno:
        allOf:
        - $ref: '#/definitions/models.PerfilAlumno'
        description: Perfiles adicionales cargados dinámicamente según rol
      perfil_creador:
        $ref: '#/definitions/models.PerfilCreador'
      role:
        type: string
      telefono:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Gateway unificada para el sistema de Formación Integral (TDIs)
    de la UTEQ.
  title: API Gateway TDI UTEQ
  version: "1.0"
paths:
  /api/tdi/catalogo:
    get:
      consumes:
      - application/json
      description: Obtiene todas las actividades vigentes con filtros opcionales
      parameters:
      - description: Filtrar por ID de Categoría
        in: query
        name: categoria_id
        type: string
      - description: Filtrar por ID de Dimensión
        in: query
        name: dimension_id
        type: string
      - description: Filtrar por ID de Entorno
        in: query
        name: entorno_id
        type: string
      - description: Filtrar por ID de Trascendencia
        in: query
        name: trascendencia_id
        type: string
      - description: Buscador por nombre o descripción
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.CatalogItem'
            type: array
        "500":
          description: Error interno
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Listar y filtrar catálogo de TDIs
      tags:
      - tdi-catalog
    post:
      consumes:
      - application/json
      description: Inserta una actividad al catálogo general verificando el rol del
        usuario en la base de datos
      parameters:
      - description: ID del usuario que ejecuta la acción
        in: header
        name: X-User-Id
        required: true
        type: string
      - description: Datos de la actividad
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.saveTDIReq'
      produces:
      - application/json
      responses:
        "201":
          description: Actividad creada
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: No autorizado
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error interno
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Registrar nueva TDI en catálogo
      tags:
      - tdi-catalog
  /api/tdi/catalogo/{id}:
    delete:
      description: Elimina físicamente o expira lógicamente una actividad si ya tiene
        alumnos registrados
      parameters:
      - description: Rol de usuario
        in: header
        name: X-User-Role
        required: true
        type: string
      - description: ID de la TDI a borrar
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Actividad eliminada
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Eliminar una TDI del catálogo
      tags:
      - tdi-catalog
    get:
      description: Obtiene los detalles de una actividad específica del catálogo
      parameters:
      - description: ID de la TDI
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.CatalogItem'
        "404":
          description: No encontrada
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtener detalle de una TDI del catálogo
      tags:
      - tdi-catalog
    put:
      consumes:
      - application/json
      description: Actualiza los campos de una actividad específica del catálogo verificando
        el rol del usuario en la BD
      parameters:
      - description: ID del usuario que ejecuta la acción
        in: header
        name: X-User-Id
        required: true
        type: string
      - description: ID de la TDI a editar
        in: path
        name: id
        required: true
        type: string
      - description: Datos actualizados
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.saveTDIReq'
      produces:
      - application/json
      responses:
        "200":
          description: Actividad actualizada
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Editar una TDI del catálogo
      tags:
      - tdi-catalog
  /api/tdi/registro/{id}/subir-evidencia:
    post:
      consumes:
      - multipart/form-data
      description: Recibe un archivo (PDF, JPG, PNG, Word, Excel), lo renombra usando
        la matrícula del alumno, calcula su hash y lo guarda localmente.
      parameters:
      - description: ID del alumno que ejecuta la acción
        in: header
        name: X-User-Id
        required: true
        type: string
      - description: ID del registro de participación (registro_tdi_id)
        in: path
        name: id
        required: true
        type: string
      - description: Archivo de evidencia (Max 5MB)
        in: formData
        name: archivo
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Evidencia subida y estado actualizado
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Cuerpo o archivo inválido
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error interno al guardar
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Subir archivo de evidencia (Autohospedado)
      tags:
      - tdi-catalog
  /api/tdi/registro/seleccionar:
    post:
      consumes:
      - application/json
      description: Asocia una actividad del catálogo a la cuenta de un alumno
      parameters:
      - description: ID del alumno que ejecuta la acción
        in: header
        name: X-User-Id
        required: true
        type: string
      - description: ID de la actividad a seleccionar
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.selectTDIReq'
      produces:
      - application/json
      responses:
        "200":
          description: Actividad seleccionada
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error interno
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Seleccionar una actividad
      tags:
      - tdi-catalog
  /api/users/administrativos/completar-perfil:
    post:
      consumes:
      - application/json
      description: Registra o actualiza el cargo de un usuario administrativo
      parameters:
      - description: ID de usuario inyectado por el Gateway
        in: header
        name: X-User-Id
        required: true
        type: string
      - description: Datos del administrativo
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.completarAdministrativoReq'
      produces:
      - application/json
      responses:
        "200":
          description: Perfil completado
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Datos inválidos
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: No autorizado
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error interno
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Completar perfil de administrativo
      tags:
      - users
  /api/users/alumnos/completar-perfil:
    post:
      consumes:
      - application/json
      description: Registra o actualiza la información académica de un estudiante
      parameters:
      - description: ID de usuario inyectado por el Gateway
        in: header
        name: X-User-Id
        required: true
        type: string
      - description: Datos académicos del alumno
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.completarPerfilReq'
      produces:
      - application/json
      responses:
        "200":
          description: Perfil completado
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Datos inválidos
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: No autorizado
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error interno
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Completar perfil del alumno
      tags:
      - users
  /api/users/creadores/completar-perfil:
    post:
      consumes:
      - application/json
      description: Registra o actualiza los datos de institución del creador
      parameters:
      - description: ID de usuario inyectado por el Gateway
        in: header
        name: X-User-Id
        required: true
        type: string
      - description: Datos del creador
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.completarCreadorReq'
      produces:
      - application/json
      responses:
        "200":
          description: Perfil completado
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Datos inválidos
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: No autorizado
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error interno
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Completar perfil de creador de TDI
      tags:
      - users
  /api/users/login:
    post:
      consumes:
      - application/json
      description: Valida credenciales y emite un JWT
      parameters:
      - description: Credenciales
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.loginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.tokenResp'
        "400":
          description: Cuerpo inválido
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Credenciales inválidas
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error interno
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Iniciar sesión
      tags:
      - users
  /api/users/logout:
    post:
      consumes:
      - application/json
      description: Invalida el token JWT actual agregándolo a la denylist de Redis
        o de memoria.
      produces:
      - application/json
      responses:
        "200":
          description: Sesión cerrada con éxito
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Token inválido o no proporcionado
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error interno al invalidar
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Cerrar sesión (Logout)
      tags:
      - auth
  /api/users/me:
    get:
      description: Devuelve el perfil del usuario autenticado
      parameters:
      - description: ID de usuario inyectado por el Gateway
        in: header
        name: X-User-Id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "401":
          description: Falta identidad
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Usuario no encontrado
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtener perfil actual
      tags:
      - users
  /api/users/register:
    post:
      consumes:
      - application/json
      description: Crea un nuevo usuario y emite un token JWT
      parameters:
      - description: Datos de registro
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.registerReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.tokenResp'
        "400":
          description: Cuerpo o datos inválidos
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: El email ya está registrado
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error interno
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Registrar un nuevo usuario
      tags:
      - users
  /api/users/users/{id}:
    delete:
      consumes:
      - application/json
      description: Cambia el estado del usuario a inactivo (Solo Administrativo o
        Coordinador)
      parameters:
      - description: Rol del usuario que ejecuta la acción
        in: header
        name: X-User-Role
        required: true
        type: string
      - description: ID del usuario a desactivar
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Usuario desactivado
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Acceso denegado
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error interno
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Desactivar un usuario (Baja Lógica)
      tags:
      - users
securityDefinitions:
  Bearer:
    description: Escribe 'Bearer ' seguido de tu token JWT obtenido en el login.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
