// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/tdi/alumnos/progreso": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retorna la meta de puntos, puntos totales y el desglose de puntos por cada dimensión del alumno logueado.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alumnos-info"
                ],
                "summary": "Obtener progreso de puntos del alumno",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del usuario (Alumno)",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Progreso de puntos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "No autorizado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tdi/catalogo": {
            "get": {
                "description": "Obtiene todas las actividades vigentes con filtros opcionales",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tdi-catalog"
                ],
                "summary": "Listar y filtrar catálogo de TDIs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filtrar por ID de Categoría",
                        "name": "categoria_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por ID de Dimensión",
                        "name": "dimension_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por ID de Entorno",
                        "name": "entorno_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por ID de Trascendencia",
                        "name": "trascendencia_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Buscador por nombre o descripción",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CatalogItem"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Inserta una actividad al catálogo general verificando el rol del usuario en la base de datos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tdi-catalog"
                ],
                "summary": "Registrar nueva TDI en catálogo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del usuario que ejecuta la acción",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Datos de la actividad",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.saveTDIReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Actividad creada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "No autorizado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tdi/catalogo/{id}": {
            "get": {
                "description": "Obtiene los detalles de una actividad específica del catálogo",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tdi-catalog"
                ],
                "summary": "Obtener detalle de una TDI del catálogo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la TDI",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.CatalogItem"
                        }
                    },
                    "404": {
                        "description": "No encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Actualiza los campos de una actividad específica del catálogo verificando el rol del usuario en la BD",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tdi-catalog"
                ],
                "summary": "Editar una TDI del catálogo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del usuario que ejecuta la acción",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID de la TDI a editar",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos actualizados",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.saveTDIReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Actividad actualizada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Elimina físicamente o expira lógicamente una actividad si ya tiene alumnos registrados",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tdi-catalog"
                ],
                "summary": "Eliminar una TDI del catálogo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rol de usuario",
                        "name": "X-User-Role",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID de la TDI a borrar",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Actividad eliminada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tdi/registro/mis-registros": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retorna el historial de inscripciones a actividades del alumno logueado, con su respectivo estado.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alumnos-info"
                ],
                "summary": "Listar registros/inscripciones del alumno",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del usuario (Alumno)",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de inscripciones",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "401": {
                        "description": "No autorizado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tdi/registro/seleccionar": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Asocia una actividad del catálogo a la cuenta de un alumno",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tdi-catalog"
                ],
                "summary": "Seleccionar una actividad",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del alumno que ejecuta la acción",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "ID de la actividad a seleccionar",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.selectTDIReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Actividad seleccionada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tdi/registro/{id}/subir-evidencia": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Recibe un archivo (PDF, JPG, PNG, Word, Excel), lo renombra usando la matrícula del alumno, calcula su hash y lo guarda localmente.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tdi-catalog"
                ],
                "summary": "Subir archivo de evidencia (Autohospedado)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del alumno que ejecuta la acción",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID del registro de participación (registro_tdi_id)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Archivo de evidencia (Max 5MB)",
                        "name": "archivo",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Evidencia subida y estado actualizado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Cuerpo o archivo inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno al guardar",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tdi/revisiones/pendientes": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retorna el listado de revisiones manuales en estado PENDIENTE (Solo Administrativos, Coordinadores o Creadores)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "revisiones"
                ],
                "summary": "Listar evidencias pendientes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rol del usuario que ejecuta",
                        "name": "X-User-Role",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de revisiones",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.PendingRevision"
                            }
                        }
                    },
                    "403": {
                        "description": "Acceso denegado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tdi/revisiones/{id}/dictamen": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Aprueba o rechaza una revisión de evidencia asignando puntos/horas de forma automática en caso de aprobación.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "revisiones"
                ],
                "summary": "Dictaminar una revisión manual",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del administrativo",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Rol del usuario que ejecuta",
                        "name": "X-User-Role",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID de la revisión",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cuerpo del dictamen",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.DictamenReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dictamen guardado con éxito",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Datos de entrada inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Acceso denegado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "db.CatalogItem": {
            "type": "object",
            "properties": {
                "categoria_id": {
                    "type": "string"
                },
                "creador_id": {
                    "type": "string"
                },
                "descripcion": {
                    "type": "string"
                },
                "dimension_id": {
                    "type": "string"
                },
                "entorno_id": {
                    "type": "string"
                },
                "evidencia_requerida": {
                    "type": "string"
                },
                "fecha_creacion": {
                    "type": "string"
                },
                "fecha_vencimiento": {
                    "type": "string"
                },
                "horas": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "puntaje": {
                    "type": "integer"
                },
                "trascendencia_id": {
                    "type": "string"
                }
            }
        },
        "db.PendingRevision": {
            "type": "object",
            "properties": {
                "apellido_materno": {
                    "type": "string"
                },
                "apellido_paterno": {
                    "type": "string"
                },
                "evidencia_nombre": {
                    "type": "string"
                },
                "evidencia_url": {
                    "type": "string"
                },
                "fecha_solicitud": {
                    "type": "string"
                },
                "matricula": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "ocr_observaciones": {
                    "type": "string"
                },
                "registro_tdi_id": {
                    "type": "string"
                },
                "revision_id": {
                    "type": "string"
                },
                "tdi_horas": {
                    "type": "integer"
                },
                "tdi_nombre": {
                    "type": "string"
                },
                "tdi_puntaje": {
                    "type": "integer"
                }
            }
        },
        "handlers.DictamenReq": {
            "type": "object",
            "required": [
                "decision"
            ],
            "properties": {
                "comentario": {
                    "type": "string"
                },
                "decision": {
                    "type": "string"
                }
            }
        },
        "handlers.saveTDIReq": {
            "type": "object",
            "properties": {
                "categoria_id": {
                    "type": "string"
                },
                "descripcion": {
                    "type": "string"
                },
                "dimension_id": {
                    "type": "string"
                },
                "entorno_id": {
                    "type": "string"
                },
                "evidencia_requerida": {
                    "type": "string"
                },
                "fecha_vencimiento": {
                    "description": "Formato AAAA-MM-DD",
                    "type": "string"
                },
                "horas": {
                    "type": "integer"
                },
                "nombre": {
                    "type": "string"
                },
                "puntaje": {
                    "type": "integer"
                },
                "trascendencia_id": {
                    "type": "string"
                }
            }
        },
        "handlers.selectTDIReq": {
            "type": "object",
            "properties": {
                "catalogo_tdi_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Escribe 'Bearer ' seguido de tu token JWT para autenticarte.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "TDI Service API",
	Description:      "Servicio de Gestión de Actividades e Integración de TDIs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
