// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/users/administrativos/completar-perfil": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Registra o actualiza el cargo de un usuario administrativo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Completar perfil de administrativo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de usuario inyectado por el Gateway",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Datos del administrativo",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.completarAdministrativoReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Perfil completado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Datos inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "No autorizado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/users/alumnos/completar-perfil": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Registra o actualiza la información académica de un estudiante",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Completar perfil del alumno",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de usuario inyectado por el Gateway",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Datos académicos del alumno",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.completarPerfilReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Perfil completado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Datos inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "No autorizado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/users/creadores/completar-perfil": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Registra o actualiza los datos de institución del creador",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Completar perfil de creador de TDI",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de usuario inyectado por el Gateway",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Datos del creador",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.completarCreadorReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Perfil completado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Datos inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "No autorizado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/users/login": {
            "post": {
                "description": "Valida credenciales y emite un JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Iniciar sesión",
                "parameters": [
                    {
                        "description": "Credenciales",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.loginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.tokenResp"
                        }
                    },
                    "400": {
                        "description": "Cuerpo inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Credenciales inválidas",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/users/logout": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Invalida el token JWT actual agregándolo a la denylist para que no pueda volver a usarse.",
                "tags": [
                    "auth"
                ],
                "summary": "Cerrar sesión (Logout)",
                "responses": {
                    "200": {
                        "description": "Sesión cerrada con éxito",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Token inválido o no proporcionado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/users/me": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Devuelve el perfil del usuario autenticado",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Obtener perfil actual",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de usuario inyectado por el Gateway",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "401": {
                        "description": "Falta identidad",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Usuario no encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/users/notificaciones": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retorna el listado de alertas y notificaciones del usuario autenticado.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notificaciones"
                ],
                "summary": "Obtener notificaciones del usuario",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del usuario logueado",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de notificaciones",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Notification"
                            }
                        }
                    },
                    "401": {
                        "description": "No autorizado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/users/notificaciones/{id}/leer": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Cambia el estado de leída a true para la notificación provista en la ruta.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notificaciones"
                ],
                "summary": "Marcar notificación como leída",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del usuario logueado",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID de la notificación",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Notificación marcada como leída",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "No autorizado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/users/register": {
            "post": {
                "description": "Crea un nuevo usuario y emite un token JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Registrar un nuevo usuario",
                "parameters": [
                    {
                        "description": "Datos de registro",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.registerReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.tokenResp"
                        }
                    },
                    "400": {
                        "description": "Cuerpo o datos inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "El email ya está registrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/users/users/{id}": {
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Cambia el estado del usuario a inactivo (Solo Administrativo o Coordinador)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Desactivar un usuario (Baja Lógica)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rol del usuario que ejecuta la acción",
                        "name": "X-User-Role",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID del usuario a desactivar",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usuario desactivado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Acceso denegado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.completarAdministrativoReq": {
            "type": "object",
            "properties": {
                "cargo": {
                    "type": "string"
                }
            }
        },
        "handlers.completarCreadorReq": {
            "type": "object",
            "properties": {
                "descripcion": {
                    "type": "string"
                },
                "institucion": {
                    "type": "string"
                },
                "tipo": {
                    "description": "Maestro, Tutor, Externa, etc.",
                    "type": "string"
                }
            }
        },
        "handlers.completarPerfilReq": {
            "type": "object",
            "properties": {
                "carrera": {
                    "type": "string"
                },
                "cuatrimestre": {
                    "type": "integer"
                },
                "grupo": {
                    "type": "string"
                },
                "matricula": {
                    "type": "string"
                },
                "tutor": {
                    "type": "string"
                }
            }
        },
        "handlers.loginReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handlers.registerReq": {
            "type": "object",
            "properties": {
                "apellido_materno": {
                    "type": "string"
                },
                "apellido_paterno": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "telefono": {
                    "type": "string"
                }
            }
        },
        "handlers.tokenResp": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "models.Notification": {
            "type": "object",
            "properties": {
                "fecha": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "leida": {
                    "type": "boolean"
                },
                "mensaje": {
                    "type": "string"
                },
                "titulo": {
                    "type": "string"
                },
                "usuario_id": {
                    "type": "string"
                }
            }
        },
        "models.PerfilAdministrativo": {
            "type": "object",
            "properties": {
                "cargo": {
                    "type": "string"
                }
            }
        },
        "models.PerfilAlumno": {
            "type": "object",
            "properties": {
                "carrera": {
                    "type": "string"
                },
                "cuatrimestre": {
                    "type": "integer"
                },
                "grupo": {
                    "type": "string"
                },
                "horas_acumuladas": {
                    "type": "integer"
                },
                "matricula": {
                    "type": "string"
                },
                "meta_horas": {
                    "type": "integer"
                },
                "tutor": {
                    "type": "string"
                }
            }
        },
        "models.PerfilCreador": {
            "type": "object",
            "properties": {
                "descripcion": {
                    "type": "string"
                },
                "institucion": {
                    "type": "string"
                },
                "tipo": {
                    "type": "string"
                }
            }
        },
        "models.Role": {
            "type": "string",
            "enum": [
                "ALUMNO",
                "ADMINISTRATIVO",
                "CREADOR_TDI",
                "COORDINADOR"
            ],
            "x-enum-varnames": [
                "RoleAlumno",
                "RoleAdministrativo",
                "RoleCreadorTDI",
                "RoleCoordinador"
            ]
        },
        "models.User": {
            "type": "object",
            "properties": {
                "activo": {
                    "type": "boolean"
                },
                "apellido_materno": {
                    "type": "string"
                },
                "apellido_paterno": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "perfil_administrativo": {
                    "$ref": "#/definitions/models.PerfilAdministrativo"
                },
                "perfil_alumno": {
                    "description": "Perfiles adicionales cargados dinámicamente según rol",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.PerfilAlumno"
                        }
                    ]
                },
                "perfil_creador": {
                    "$ref": "#/definitions/models.PerfilCreador"
                },
                "role": {
                    "$ref": "#/definitions/models.Role"
                },
                "telefono": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Escribe 'Bearer ' seguido de tu token JWT para autenticarte.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "User Service API",
	Description:      "Microservicio de autenticación y gestión de usuarios.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
